name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in the root directory
        run: ls -la

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
